import "./styles/globals.css";

export const metadata = {
  title: "Meditation",
  description: "Generated by N1SHA-git",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="h-dvh font-[AlegreyaSans] bg-[url('/images/welcome-bg.jpg')] 
          bg-cover bg-center bg-no-repeat antialiased"
      >
        {children}
      </body>
    </html>
  );
}
